# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - "deploy-prod"
  before_script:
    - whoami
    - cd $WORK_DIR 
    - systemctl stop avefi-frontend
  script:
    #- cd $WORK_DIR
    - cd $WORK_DIR
    - ls -la    
    - yarn update
    - yarn build
    - yarn start
  after_script:
    - systemctl start avefi-frontend

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  only:
    - main
  tags:
    - "deploy-prod"
  before_script:
    - whoami
    #- apt-get -yq update
    #- apt-get -yqq install ssh
    #- install -m 600 -D /dev/null ~/.ssh/id_ed25519
    #- whoami
    #- echo "$SSH_PRIVATE_KEY_ED25519" | base64 -d > /home/gitlab-runner/.ssh/id_ed25519
    #- ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
    #- ssh-keyscan -t ed25519 avefi-server >> /home/gitlab-runner/.ssh/known_hosts
    #- chmod 644 /home/gitlab-runner/.ssh/known_hosts
  script:
    - whoami
    #- ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd $WORK_DIR && git checkout $MAIN_BRANCH && git pull && exit"
    - whoami

