services:
  av-efi-frontend:
    container_name: av-efi-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - './components:/app/components'
      - './logs:/app/logs'
    networks:
      - proxy-network
    command: yarn dev --host 0.0.0.0


networks:
  proxy-network:
    name: proxy-network
    external: true
