# see cms project for docker containers
ARG NODE_VERSION=18.20.5

# Create build stage
FROM node:${NODE_VERSION}-slim AS base

ENV NODE_ENV=development

WORKDIR /app

# Build
FROM base AS build

COPY --link ./package.json ./yarn.lock ./.yarnrc.yml ./
RUN corepack enable
RUN yarn set version berry
RUN yarn install

# Run
FROM base

COPY --from=build /app/node_modules /app/node_modules

CMD [ "npm", "run", "dev" ]