ARG NODE_VERSION=18.20.5
FROM node:${NODE_VERSION}-slim

ENV NODE_ENV=development
WORKDIR /app

# Enable corepack (optional if not using pre-installed yarn)
RUN corepack enable

# Copy config and lockfiles early for cache
COPY .yarnrc.yml ./
COPY package.json yarn.lock ./

# Clean bad cache (optional but safe)
RUN rm -f .pnp.* && rm -rf .yarn/cache

# Install dependencies
RUN yarn install

# Copy the full source
COPY . .

EXPOSE 3000 24678

CMD ["yarn", "dev"]
