version: "3.9"

services:
  av-efi-frontend:
    container_name: av-efi-frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: rebuild
          path: yarn.lock
    ports:
      - 127.0.0.1:3000:3000      # Nuxt dev server
      - 127.0.0.1:24678:24678    # Vite HMR websocket
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - AUTH_BASE_URL=http://av-efi-backend:8000
      - NODE_ENV=development
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
    external: true

volumes:
  node_modules:
