services:
  av-efi-frontend:
    container_name: avefi-frontend
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 3000:3000
    volumes:
      - './components:/app/components'
      - './logs:/app/logs'
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
    external: true
