services:
  av-efi-frontend:
    container_name: av-efi-frontend
    build:
      context: .
      dockerfile: DockerFile.dev
    develop:
      watch:
        - action: sync
          path: ./components
          target: /app/components
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:24678:24678
    volumes:
      - '.:/app'
      - node_modules:/app/node_modules
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
    external: true

volumes:
  node_modules:
