/**
 * AUTO-GENERATED by scripts/generate-schema-severity.mjs.
 *
 * Source of truth: models/interfaces/schema/model.yaml.
 * Do not hand-edit severity values here; update model.yaml or the ES field
 * inventory in the generator, then run npm run generate:schema-severity.
 */

import type { SchemaLevel } from './report-utils';

export type { SchemaLevel };

export const REQUIRED_SCHEMA_SLOTS = [
  'category',
  'has_agent',
  'has_issuer_id',
  'has_issuer_name',
  'has_name',
  'has_record',
  'has_unit',
  'has_value',
  'is_item_of',
  'is_manifestation_of',
] as const;

export const REQUIRED_SCHEMA_SLOT_USAGE = {
  Activity: ['type'],
  AuthorityResource: ['id'],
  PreservationEvent: ['type'],
  PublicationEvent: ['type'],
  RightsCopyrightRegistrationEvent: ['has_activity'],
  Title: ['type'],
  WorkVariant: ['has_primary_title', 'type'],
} as const;

export const ES_FIELD_SCHEMA_LEVEL: Record<string, SchemaLevel> = {
  'castmembers.keyword': 'info',
  'directors_or_editors.keyword': 'info',
  'handle.keyword': 'warning',
  'has_record.described_by.has_issuer_id.keyword': 'error',
  'has_record.described_by.has_issuer_name.keyword': 'error',
  'has_record.described_by.has_source_key.keyword': 'warning',
  'has_record.has_alternative_title.has_name.keyword': 'info',
  'has_record.has_event.has_activity.has_agent.has_alternate_name.keyword': 'info',
  'has_record.has_event.has_activity.has_agent.has_name.keyword': 'error',
  'has_record.has_event.located_in.has_name.keyword': 'info',
  'has_record.has_form.keyword': 'info',
  'has_record.has_genre.has_name.keyword': 'info',
  'has_record.has_primary_title.has_name.keyword': 'error',
  'has_record.has_subject.has_name.keyword': 'info',
  'has_record.same_as.id.keyword': 'warning',
  'has_record.type.keyword': 'error',
  'kip.keyword': 'info',
  'manifestations.handle.keyword': 'warning',
  'manifestations.has_record.described_by.has_issuer_name.keyword': 'error',
  'manifestations.has_record.described_by.has_source_key.keyword': 'warning',
  'manifestations.has_record.has_colour_type.keyword': 'warning',
  'manifestations.has_record.has_event.type.keyword': 'warning',
  'manifestations.has_record.has_primary_title.has_name.keyword': 'warning',
  'manifestations.has_record.has_sound_type.keyword': 'warning',
  'manifestations.has_record.is_manifestation_of.id.keyword': 'error',
  'manifestations.items.handle.keyword': 'warning',
  'manifestations.items.has_record.described_by.has_issuer_name.keyword': 'error',
  'manifestations.items.has_record.described_by.has_source_key.keyword': 'warning',
  'manifestations.items.has_record.element_type.keyword': 'warning',
  'manifestations.items.has_record.has_access_status.keyword': 'warning',
  'manifestations.items.has_record.has_duration.has_value.keyword': 'info',
  'manifestations.items.has_record.has_extent.has_value.keyword': 'info',
  'manifestations.items.has_record.has_format.type.keyword': 'info',
  'manifestations.items.has_record.has_primary_title.has_name.keyword': 'warning',
  'manifestations.items.has_record.in_language.code.keyword': 'warning',
  'manifestations.items.has_record.is_item_of.id.keyword': 'error',
  'manifestations.items.kip.keyword': 'info',
  'manifestations.items.url.keyword': 'info',
  'production.keyword': 'info',
  'subjects.keyword': 'info',
  'url.keyword': 'info',
};

export function schemaLevelForField(field: string, fallback: SchemaLevel = 'info'): SchemaLevel {
  return ES_FIELD_SCHEMA_LEVEL[field] ?? fallback;
}
